### ISSUE TITLE
Could it support the redmine 2.0.3?

### ISSUE THREAD

**Issue by archonwang** [k41n/redmine_milestones#1]
Could it support the redmine 2.0.3? I am not sure whether it could support the redmine 2.0.3. with rails 3.2.6? any idea?
Thanks

**Comment by k41n** [comment]
Migration to 3.x branch can be done, but it is not yet. In roadmap, yes.

**Comment by k41n** [comment]
Try new branch redmine-2.x. That is quite a new one, so if some bugs are found, let me know and I will fix them ASAP.

**Comment by archonwang** [comment]
OK. I will test it ASAP. THANKS
