### ISSUE TITLE
Error 500 when trying to create a milestone (version 2.0.3)

### ISSUE THREAD

**Issue by petscare** [k41n/redmine_milestones#12]
Error 500 when trying to create a milestone (version 2.0.3)

**Comment by alexbevi** [comment]
This is fixed in https://github.com/alexbevi/redmine_milestones/commit/6b876773b88154e875351127ac7371c48a5f752e.

Not going to bother with a pull request yet as it's just removing 2 lines ;)

**Comment by petscare** [comment]
Cool , Thanks for your help, It's work for redmine 2.0.3 when i create a milestone on project setting.
