### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by stf675** [k41n/redmine_milestones#2]
when trying to see all issues or gantt chart for all issues

  Parameters: {"controller"=>"gantts", "action"=>"show"}

NoMethodError (undefined method `milestones' for nil:NilClass):
  app/helpers/queries_helper.rb:124:in`build_query_from_params'
  app/helpers/queries_helper.rb:92:in `retrieve_query'
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in`dispatch_cgi'

 Parameters: {"controller"=>"issues", "action"=>"index", "set_filter"=>"1"}

NoMethodError (undefined method `milestones' for nil:NilClass):
  app/helpers/queries_helper.rb:124:in`build_query_from_params'
  app/helpers/queries_helper.rb:92:in `retrieve_query'
  app/controllers/issues_controller.rb:57:in`index'
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

**Comment by k41n** [comment]
Hello! Could you please provide redmine version for me to try to reproduce problem?

**Comment by k41n** [comment]
Looks alike you are using Redmine 2.x with Rails 3.x. For that case you should use branch redmine-2.x. I tested it slightly, but if you are so kind and try it, I will do my best to fix any problem found.

**Comment by stf675** [comment]
my redmine is 1.4.1

one of the guys on redmine forum noticed that:

The problem is the ORDER BY `lft` part, because it's missing its alias. There are 2 columns called 'lft', one in issues, and one in projects and the database engine can't decide which of both to use for the order clause...

**Comment by stf675** [comment]
still same problem after latest version.  individual project gantt/calendar/view all issues works ok.

error comes up when viewing for all

Processing IssuesController#index (for xxx.xxx.xxx.xxx at 2012-07-23 09:26:08) [GET]
  Parameters: {"set_filter"=>"1", "action"=>"index", "controller"=>"issues"}

NoMethodError (undefined method `milestones' for nil:NilClass):
  app/helpers/queries_helper.rb:124:in`build_query_from_params'
  app/helpers/queries_helper.rb:92:in `retrieve_query'
  app/controllers/issues_controller.rb:57:in`index'
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

Rendering C:/Program Files/BitNami Redmine Stack/apps/redmine/public/500.html (500 Internal Server Error)

Processing CalendarsController#show (for xxx.xxx.xxx.xxx at 2012-07-23 09:26:11) [GET]
  Parameters: {"action"=>"show", "controller"=>"calendars"}

NoMethodError (undefined method `milestones' for nil:NilClass):
  app/helpers/queries_helper.rb:124:in`build_query_from_params'
  app/helpers/queries_helper.rb:92:in `retrieve_query'
  app/controllers/calendars_controller.rb:42:in`show'
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

Rendering C:/Program Files/BitNami Redmine Stack/apps/redmine/public/500.html (500 Internal Server Error)

Processing GanttsController#show (for xxx.xxx.xxx at 2012-07-23 09:26:14) [GET]
  Parameters: {"action"=>"show", "controller"=>"gantts"}

NoMethodError (undefined method `milestones' for nil:NilClass):
  app/helpers/queries_helper.rb:124:in`build_query_from_params'
  app/helpers/queries_helper.rb:92:in `retrieve_query'
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in`dispatch_cgi'

Rendering C:/Program Files/BitNami Redmine Stack/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by k41n** [comment]
It seems I was not careful enough and didn't noticed situation where problem arised. Indeed, at any pages with issues not inside project the error mentioned had arised. Should be fixed now, please give a feedback if it helps.

**Comment by stf675** [comment]
tried to replace one file - got error on plugin migration.

replaced the whole plugin folder and rerun migration - works perfectly.  Thanks

**Comment by k41n** [comment]
Ok, thanks for pointing me errors, closing than.
