### ISSUE TITLE
Please add screeners and more description

### ISSUE THREAD

**Issue by cforce** [k41n/redmine_milestones#3]
How does this adaance st redmine version which also can have and end dates.

**Comment by k41n** [comment]
Added some screenshots on redmine.org (http://www.redmine.org/plugins/redmine_milestones)

Version dates are just a recommendations for milestones. You can see confirmation when you set milestone start or end date out of  version timeframe, but you can ignore them and set anyway. Besides, there can be aggregate milestones not assigned to any specific version, having many children milestones to conventrate control over some different projects in one point.
